# Get HTML home page
GET http://localhost:8080/polls/

###

# Get lists of questions
GET http://localhost:8080/v1/question/

###

# Get Question with specific ID

GET http://localhost:8080/v1/question/2

###

POST http://localhost:8080/v1/question/
Content-Type: application/json

{
  "question_text": "What is your favorite programming language?",
  "choices": ["Python", "JavaScript", "Java"]
}



###
# Update Question with specific ID
PUT http://localhost:8080/v1/question/6
Content-Type: application/json

{
  "question_text": "Sample Testing !"
}

###
# Delete Question with Specific ID
DELETE http://localhost:8080/v1/question/5

###
# Up/Down Vote Question
# If you want to up-vote -> 1 || down-vote -> 0

POST http://localhost:8080/v1/vote/
Content-Type: application/json

{
  "question_id": 6,
  "choice_id": 1,
  "vote": 1
}

###



